# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

scan_timeout = 1000 # milliseconds

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
RedHatEnterprise = " "
Redhat = " "
Redox = "󰀘 "
SUSE = " "
Solus = "󰠳 "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
openSUSE = " "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[character]
error_symbol = "[✘](red)"
success_symbol = "[❯](green)"
vimcmd_symbol = "[❮](green)"

[battery]
disabled = true

[shell]
disabled = false
format = "[$indicator]($style) "

# Nerd Font Devicons Bash icon
bash_indicator = " "   # nf-dev-bash
zsh_indicator  = ""    # generic shell icon for Zsh
style = "bold green"

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true
